source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Mapwize_Example', :exclusive => true do
  pod 'Mapwize', :path => '../'
end

target 'Mapwize_Tests', :exclusive => true do
  pod 'Mapwize', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
